[project]
name = "collaborative-filtering-ml100k"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "kagglehub>=0.3.12",
    "notebook>=7.4.2",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
]
